# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f533fe3cdd7c0c5e8d14af1cd4c589c05ea2db7baf561015d2e1bab05134f7b8da85be8a113e5adb31f6993c6e68779bd3395a0c9a4c8d657039e862b433aceb

test:
  secret_key_base: 71899d88c1d972f5acb4df5fe15d05b287aba5787d946b6782e29b102889cd2743b7e75b19cae0cbaa886ea5668513a173464a68bdf0f7fbb8eadf8f232b6f9a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
